version: "3.9"
services:
  web:
    build: ./webserver
    ports:
      - "80:80"
    #volumes:
    #  - ./filestore:/var/www/html/10.0/filestore
  
  sql:
    build: ./mysql
    ports:
    - "3306:3306"
  #  volumes:
  #    - ./db/:/var/lib/mysql

